### ISSUE TITLE
Handle vault registration on the Badger subgraph for a new registry

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-api#1219]
# Summary

Any new vaults for Badger (or Citadel) will be added to new v2 registry contracts.
Handling for multiple new v2 registries will be required.

## Requirements

- Account for event processing on all registries on any official badger v2 registry contract

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-subgraph/pull/50

**Comment by NamelsKing** [comment]
Last thing that left is to update config with addresses of registryV2 and deployedAt blocks

**Comment by axejintao** [comment]
@NamelsKing i think we can close it now?
