### ISSUE TITLE
Utilize production vaults as source of truth for API vault definitions

### ISSUE THREAD

**Issue by okjintao** [Badger-Finance/badger-api#1220]
# Summary

Utilize the v2 registry as a source of truth for Vault defintions.
The existing hard coded vault definitions should no longer be utilized.

Instead, the registry should be periodically scanned and used to create these new vault definitions in tables.

## Requirements

- Capture some new time based metrics: createdAt, lastUpdatedAt, releasedAt
- Derive vault name, protocol, and behavior from vault on chain metadata
- Determine "newness" of vault based on recent promotion to "open" status, a new vault "releasedAt" is within the last two weeks
- Dynamically assign balance look updates from the protocols ascribed to vaults via the metadata

## Tasks

- Create a new (temporary) registry service for the sdk utilizing and implementing new registry lookups
  - Fully support all registry view functions
  - Support metadata parsing
- Independent integration with registry v2 
  - Utilize new infrastructure to directly utilize new charting library
- Remove old registry service (post migration)
- Remove old vault indexers / definitions (post migration)

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-sdk/pull/179

**Comment by NamelsKing** [comment]
Subgraph part - https://github.com/Badger-Finance/badger-subgraph/pull/50

**Comment by NamelsKing** [comment]
API - https://github.com/Badger-Finance/badger-api/pull/1282
