### ISSUE TITLE
Utilize production vaults as source of truth for vault keepers operations

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-api#1221]
# Summary

Utilizing the v2 registry, remove all hard coded definitions for vaults in the keepers.

## Requirements

- Read vault definitions from new v2 registry
- v1 vaults utilize existing legacy keeper behavior
- v1.5 vaults utilize badger API harvest estimations + gas estimation to harvest at economically opportune moments
- badger builders harvest log discord integration

![image](https://user-images.githubusercontent.com/6101512/170116856-a7dffdf4-4634-45ae-8db7-f21bafc2de20.png)

**Comment by NamelsKing** [comment]
ser @btcookies took that
