### ISSUE TITLE
API-3: [feat. request]: Operational Data -- Rewards Cycle Time & Harvest Time on Setts

### ISSUE THREAD

**Issue by benefacto** [Badger-Finance/badger-api#129]
### Description

Request from @BenLeibig 
"It would also be nice if you could include information around:

Rewards Cycle Time
Harvest Time on setts (harvest is for all setts per chain I think)

These are other operational data our community cares about. Maybe this doesn't fit well into changes in the API, but if you can easily build in metrics points/health checks that would be nice.

Cycles should occur every 2 hours but is sometimes late, more than 4-6 hours is bad/go red.
BSC harvests should occur ever 2 hours
ETH harvests should occur every 24 hours
These numbers should be dynamic.

This is a suggestion not a requirement."

UI implementation still TBD -- @benefacto 

#### Request Metrics 

| Metric | Rating | 
| --- | --- |
| Priority | TBD |
| Effort | TBD |
| Risk | TBD |
 
**Options:** low, medium, high

#### Documentation (optional)

Add any supporting documentation, proposed API responses, interaction diagrams etc. 

#### Resources (optional)

Add any new or updated resource requirements for the system

**Comment by axejintao** [comment]
rescope: add last harvest to vault response
