### ISSUE TITLE
Jest's tests leaking memory on run

### ISSUE THREAD

**Issue by NamelsKing** [Badger-Finance/badger-api#1295]
## Description
Coverage job on CI failing with OOM error. Need to figure out, how to fix it.

### Current Heap Output on test run:
![image](https://user-images.githubusercontent.com/18405840/176513264-efaa2a33-25c5-4c8a-812e-1f7c61a63e9a.png)

### What have been done so far:

**Reason**: `ts-jest` could be the reason,  according to this issues https://github.com/kulshekhar/ts-jest/issues/1967
**Solution**: Try to launch tests on compiled files. PR -https://github.com/Badger-Finance/badger-api/pull/1294
**Result**: Doesnt seem to help much =\ Saved about 50 mb.
![image](https://user-images.githubusercontent.com/18405840/176514148-b999350b-7f2b-4d90-8a5e-b05353758b3d.png)

**Reason**: [Jest leaks memory allocating strings for imported files](https://stackoverflow.com/questions/70939563/jest-leaks-memory-allocating-strings-for-imported-files)
**Solution**: Upgrade jest to latest version, tried to launch `node` gc manually, after each test. No effect.
**Result**: Jest 28 has new transpile flow, now memory sky high, mb missconfigured something. PR - https://github.com/Badger-Finance/badger-api/pull/1303.
1 test suite run:
![image](https://user-images.githubusercontent.com/18405840/177290636-ad71fe5c-f44f-48d8-8dcc-0dacaf04a9bc.png)

_This is heap, before upgrade_
![image](https://user-images.githubusercontent.com/18405840/176515802-462e6c8a-5802-4525-8988-48efa048620e.png)

**38%** - import strings
**22%** - source maps

### Possible solutions:
If we won't be able to apply one of the fixes above, so that it would make sense, or figure our how to cook jest correctly. Last resort, is to split tests by chunks, thus decrease consumed memory

### Note
Node 16.11+ and higher consumes 30%+ memory, so better stick with 16.10

**Comment by axejintao** [comment]
duplicate, many of these issues solved now - will close this one and track the resolution on the other ticket
