### ISSUE TITLE
feat(monitoring): Add discord hook to API.

### ISSUE THREAD

**Issue by mrbasado** [Badger-Finance/badger-api#1339]
# Background

We want to integrate a discord logging to provide notifications to developers for errors that require intervention.

AWS has secrets for the discord URL and this is already setup in [rewards repo](https://github.com/Badger-Finance/badger-rewards/blob/5601d6ac02799e574ddc240c8d4e1fcb9ba79038/helpers/discord.py#L85) but this is a python codebase. 
badger builders disocrd [channel example](https://discord.com/channels/785315893960900629/888129516617216070) 

## Requirements

- Setup the discord utility and have it grab the required information from AWS so other alerts can be setup easily by copying the example provided.

## Tasks

- [x] Setup the discord utility and have it grab the required information from AWS
- [x] Create a test hook  [here](https://github.com/Badger-Finance/badger-api/pull/1336/files#diff-c6fa2f16b0bad8b8760dab9d622879f2b7b96af9e28f8a927a39559bc9133ed1R38) this should give a discord message saying the harvest failed.

**Comment by axejintao** [comment]
thanks @mranilrai
