### ISSUE TITLE
bug: created at returning nan

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-api#1476]
# Summary

- NaN returned for tests `createdAt` snapshots
- 
https://github.com/Badger-Finance/badger-api/pull/1475/files#diff-15457127f89f7ec40d814692d1a514b89f1c4c9fff2ff04752f728153547f45bR10

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-api/pull/1499

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-subgraph/pull/60
