### ISSUE TITLE
feat(rewards): debank rewards support

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-api#967]
# Background

Badger DAO users currently cannot see their pending rewards on any chain via DeBank. The API has this information for every token available and they are willing to integrate support for our rewards if we provide them an API to do so. 

## Requirements

![image](https://user-images.githubusercontent.com/6101512/157069533-63175ce3-7915-4da4-a36f-690823d7b2aa.png)

API is provided via DeBank, is non-negotiable in terms of fields, typing etc. even if they do not conform to the code standards in the repository. 

- [ ] Provider paginated user rewards by chain
- [ ] Support querying chains via chain id

**Comment by kingikalgo** [comment]
https://github.com/Badger-Finance/badger-api/pull/1096

Released and discussed with @axejintao
