### ISSUE TITLE
feat(vaults): expose vault harvests information

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-api#974]
# Background

Users often wonder where our APY come from our how it is estimated. It is most helpful to display the vault performances by harvest to allow users to better understand the performance of the vault. 

Note: **Poorly managed vaults will of course be easier to identify if this is available :)**

## Requirements

- [x] `listVaultHarvests`: allow a full view of all vaults harvests on the requested chain
- [x] `getVaultHarvests`: allow a single vault on the requested chain, display tokens compounded per harvest, tokens emitted per tree distribution
- [x] each harvest includes a snapshot of the strategy balance at the time of harvest, the type of event (harvest, or tree distribution), the amount of token associated with the event and the estimated apr of that event

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-api/pull/1079
