### ISSUE TITLE
feat(infra): configure api gateway custom domain via serverless configuration

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-api#985]
# Background

`api.badger.com` is support via a custom domain that was manually created. Support configuring custom domains via the serverless configuration to remove this custom managed piece.

## Requirements

- [ ] Add custom domain management to serverless
- [ ] Add custom domain support for `api.badger.{com,tools,finance}`

**Comment by btcookies** [comment]
https://github.com/amplify-education/serverless-domain-manager

**Comment by ICEBADGER** [comment]
@mrbasado  can you have a look at this one and decide if still relevant or what not?

**Comment by mrbasado** [comment]
not relevant anymore
